[package]
name = "mool_codegen"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mool_ir = { path = "../mool-ir" }
llvm-sys = "130"
regex = "*"
